image: gradle:alpine

stages:
  - build
  - test

build:
  stage: build
  script:
    - apk add --update openjdk11
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
    - chmod +x gradlew
    - ./gradlew build

test:
  stage: test
  script: ./gradlew check
